In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA

In [4]:
data = load_breast_cancer(as_frame=True)

df = data.frame

df.head()

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [5]:
df.shape

(569, 31)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [7]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [8]:
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'target'],
      dtype='object')

In [9]:
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train.shape
y_test.shape

(143,)

In [10]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
columns= data.feature_names

X_train = pd.DataFrame(X_train, columns=columns)
X_test = pd.DataFrame(X_test, columns=columns)

In [12]:
X_train.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0    -0.349138     -1.438513  ...       -0.925086                -0.808411
1    -0.204687      0.312640  ...        1.149559                 1.569111
2    -0.329312     -0.215072  ...        0.534970                -0.619348
3     1.027403      2.089824  ...        0.152884                 0.421636
4     1.828969      0.696001  ...        0.050452                -1.406351

[5 rows x 30 columns]

In [13]:
X_test.tail()

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
138     0.146530     -0.936832  ...        0.443920                 0.078818
139     0.092714      0.241647  ...        3.048607                 1.022424
140    -0.873130     -0.560570  ...        0.195157                -0.258307
141     1.610875      0.698367  ...       -0.178799                -0.409785
142    -1.094057     -1.651491  ...        0.095978                -0.348852

[5 rows x 30 columns]

In [14]:
logistic = LogisticRegression()
gbc = GradientBoostingClassifier()

In [15]:
logistic.fit(X_train, y_train)
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

In [16]:
print(LogisticRegression)

y_pred_logistic = logistic.predict(X_test)

print(f' Accuracy : {accuracy_score(y_test, y_pred_logistic)}\n')
print(f'Confusion Matrix : {confusion_matrix(y_test, y_pred_logistic )}\n')
print(f'Classification Report: {classification_report(y_test, y_pred_logistic)}')

print("--------------------------------------------------------")
print(f'GradientBoostingClassifier:')
y_pred_gbc = gbc.predict(X_test)
print(f'Accuracy Score : {accuracy_score(y_test, y_pred_gbc)}')
print(f'Confusion Matrix : {confusion_matrix(y_test, y_pred_gbc)}')
print(f'Classification Report: {classification_report(y_test, y_pred_gbc)}')

<class 'sklearn.linear_model._logistic.LogisticRegression'>
 Accuracy : 0.9790209790209791

Confusion Matrix : [[53  1]
 [ 2 87]]

Classification Report:               precision    recall  f1-score   support

           0       0.96      0.98      0.97        54
           1       0.99      0.98      0.98        89

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143

--------------------------------------------------------
GradientBoostingClassifier:
Accuracy Score : 0.958041958041958
Confusion Matrix : [[51  3]
 [ 3 86]]
Classification Report:               precision    recall  f1-score   support

           0       0.94      0.94      0.94        54
           1       0.97      0.97      0.97        89

    accuracy                           0.96       143
   macro avg       0.96      0.96      0.96       143
weighted avg       0.96      0.96      0.96       143

In [17]:
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)
x_test_pca = pca.transform(X_test)

X_train_pca = pd.DataFrame(X_train_pca, columns=['PCA1', 'PCA2'])
x_test_pca = pd.DataFrame(x_test_pca, columns=['PCA1', 'PCA2'])

X_train_pca.head()

       PCA1      PCA2
0 -4.307702 -1.878763
1  2.370195  2.003231
2 -1.928674 -0.229950
3  3.373326 -1.657578
4  4.897018 -3.028985